[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['rm -rf node_modules package-lock.json', 'npm install --legacy-peer-deps']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'npm start'
